### ISSUE TITLE
In CSharp generated code, Item container to serialize by calling JsonConvert instead of .ToJson and .Parse

### ISSUE THREAD

**Issue by jeremyiverson** [Colectica/cogs#106]

**Comment by kevinchristianson** [comment]
I ran into a problem when trying to implement this. Using JsonConvert.SerializeObject and JsonConvert.DeserializeObject creates a JsonReader object which is passed to my custom JsonConverter attributes. It's simple enough to get information from a JsonReader instead of a string, however, the JsonReaders tamper with DateTime values. I was getting around this previously by using the serialized json string in parsing to get the correct values, but without access to the string, I'm not sure how to get the correct DateTime values that aren't converted to local time.
